// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
public partial class RecomandareProduse
{
    /// <summary>
    /// model input class for RecomandareProduse.
    /// </summary>
    #region model input class
    public class ModelInput
    {
        [LoadColumn(0)]
        [ColumnName(@"ClientID")]
        public float ClientID { get; set; }

        [LoadColumn(1)]
        [ColumnName(@"ProdusID")]
        public float ProdusID { get; set; }

        [LoadColumn(2)]
        [ColumnName(@"Frecventa")]
        public float Frecventa { get; set; }

    }

    #endregion

    /// <summary>
    /// model output class for RecomandareProduse.
    /// </summary>
    #region model output class
    public class ModelOutput
    {
        [ColumnName(@"ClientID")]
        public float ClientID { get; set; }

        [ColumnName(@"ProdusID")]
        public float ProdusID { get; set; }

        [ColumnName(@"Frecventa")]
        public float Frecventa { get; set; }

        [ColumnName(@"Score")]
        public float Score { get; set; }

    }

    #endregion

    private static string MLNetModelPath = Path.GetFullPath("RecomandareProduse.mlnet");

    public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


    private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
    {
        var mlContext = new MLContext();
        ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
        return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
    }

    /// <summary>
    /// Use this method to predict on <see cref="ModelInput"/>.
    /// </summary>
    /// <param name="input">model input.</param>
    /// <returns><seealso cref=" ModelOutput"/></returns>
    public static ModelOutput Predict(ModelInput input)
    {
        var predEngine = PredictEngine.Value;
        return predEngine.Predict(input);
    }
}
